### ISSUE TITLE
Train on new dataset

### ISSUE THREAD

**Issue by anjugopinath** [JunukCha/Text2HOI#6]
Can you share commands to train on a new dataset, please?

**Comment by JunukCha** [comment]
Sorry, but we don't plan to release the train code.

**Comment by James-1994** [comment]
<img width="430" alt="image" src="https://github.com/user-attachments/assets/a76332e8-e620-4ad9-80ab-07e9f52aba33">
But you have mentioned that "We will release our model and newly labeled data as a strong foundation for future research. Codes and data....". How can your work can become a foundation for future research, if your are not planning to release the train code ? This statement in the paper might be misleading.
